import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import "./index.css";
// import App from "./m18-CRUD V2/Soal 2/App";
import UpdateItem from "./m18-CRUD V2/Test";
// import { DeliveryStatus, Greeting, Notification } from "./m5/finaly.jsx";
// import RenderingList from "./m6/Try.jsx";
// import UserList from "./m6/praktek.jsx";
// import Card from "./m6/RenderingList/fragments/Card.jsx";
// // import App from "./m6/RenderingList/fragments/App.jsx";
// import Event from "./m7/try.jsx";
// import PreventDefaultExample from "./m7/praktek.jsx";
// import EventPropagationExample from "./m7/praktek2.jsx";
// import ShowAlert from "./m7/praktek3.jsx";
// import SimpleClick from "./m7/praktek4.jsx";
// // import Counter from "./m8/number.jsx";
// import ItemList from "./m8/array.js";
// // import Counter from "./m8/praktek1.jsx";
// import LoginStatus from "./m8/praktek2.js";
// import SimpleCalculator from "./m8/praktek3.jsx";
// import SimpleNameList from "./m9/Array.js";
// import UpdateStateWithMap from "./m9/Map.js";
// import ProductList from "./m9/soal1.jsx";
// // import Counter from "./m10/noeffect.jsx";
// // import WithDependency from "./m10 - UseEffect/withEffect.js";
// // import Counter from "./m10 - UseEffect/s1.jsx";
// // import CountLogger from "./m10 - UseEffect/s2.js";
// // import TextLogger from "./m10 - UseEffect/s3.js";
// // import Statusbar, { useOnlineStatus } from "./m11/Hooks.jsx";
// import useTheme from "./m11/s1.js";
// import ToggleTheme from "./m11/s1.js";
// import TaskStatusComponent from "./m11/cabang s2.js";
// // import HomePage from "./m12/privite.jsx";
// import Home from "./m12/LinkTo.js";
// // import HomePage from "./m12/s3.jsx";
// import Navigation from "./m12/s3.jsx";
// import HomePage from "./m12/s4.js";
// import DashboardPage from "./m12/s5.js";
// import NotFoundPage from "./m12/s2.js";
// // import CobaAxios from "./m13/s1.jsx";
// // import App from "./m13/s2.jsx";
// import ToggleSwitch from "./m11/s1.js";
// import DetailPage from "./m14/UseParams.jsx";
// // import App from "./m14/UseParams2.jsx";
// import CobaAxios from "./m13/Axios.js";
// import CobaUseParams from "./m14/UseParams.jsx";
// import PostDetail from "./m14/ApiDinamis.jsx";
// // import BookList from "./m14/s1.jsx";
// // import BookDetail from "./m14/s1pt2.jsx";
// // import App2 from "./m14/s1pt3.jsx";
// // import App3 from "./m14/app3.jsx";
// import DetailProducts from "./m14/s2.jsx";
// // import { BooksDetail, MapBooks } from "./m14/soal 1/components.jsx";
// import App from "./m14/soal 2/app.jsx";
// import { BooksDetail, MapBooks } from "./m14/soal 1/components.jsx";
// import SimpleUseForm from "./m15 - Post/Post.jsx";
// import Pull from "./m15 - Post/s2.jsx";
// import { ProductList } from "./m14/soal 2/components.jsx";
// import App from "./m15 - Post/s2.jsx";
// import HandleLogin from "./m16 - JWT/test.jsx";
// import AxioCard from "./m16 - JWT/s2.jsx";
// import CreateUser from "./m17-CRUD/test.jsx";
// import App from "./m17-CRUD/Soal 2/App.jsx";
// import ProductList from "./m18-CRUD V2/ProductList.jsx";
// import UpdateProduct from "./m18-CRUD V2/Soal 2/Update.jsx";
// import Home from "./m18-CRUD V2/Soal 2/Components.jsx";
// import App from "./m18-CRUD V2/Soal 1/App.jsx";
import CustomerCounter from "./m19-ZUZTAND/s1.jsx";
import Counter from "./m19-ZUZTAND/Test.jsx";
import TodoList from "./m19-ZUZTAND/s2.jsx";
// import App from "./Project/app.jsx";
import Home from "./m18-CRUD V2/Soal 2/Components.jsx";
import Help from "./m17-CRUD/Soal 1/Help.jsx";
// import App from "./m18-CRUD V2/Soal 2/App.jsx";
// import App from "./m15 - Post/s2.jsx";
// import App from "./Project/app.jsx";
// import App from "./m18-CRUD V2/Soal 2/App.jsx";
// import NewAxios from "./m17-CRUD/Soal 1/Routing.jsx";
// import { CreateUser, DeleteUser } from "./m18-CRUD V2/UserManagement.jsx"; 
// import App from "./m17-CRUD/Routing.jsx";
import NewAxios from "./m17-CRUD/Soal 1/Routing.jsx";
import App from "./Project/app.jsx";
// import App from "./m18-CRUD V2/Soal 1/App.jsx";
// import Login from "./m15 - Post/s1.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App/>
  </StrictMode>
)
